[package]
name = "analysis-ffi"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[lib]
name = "analysis_ffi"
crate-type = ["rlib"]

[dependencies]
analysis = { path = "../analysis" }

[build-dependencies]
cbindgen = "0.20.0"
dart-bindgen = "0.1.8"
